/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service welcome banner
         * @description Returns a small liveness banner at the service root (no `/api/v1` prefix). For dependency-aware readiness use GET /api/v1/health instead.
         */
        get: operations["AppController_getInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Actively pings PostgreSQL (via Prisma) and Redis. Returns 200 only when BOTH are reachable; 503 if either is down. The body reports each dependency so operators can see which one failed.
         */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/line-users/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the authenticated LINE user's access status + registration.
         * @description Header-derived and param-less: the caller reads only their own status (identity = the verified `sub`). A LIFF-first user with no prior row gets a fresh `UNREGISTERED` state and `registration: null`. The single call the client portal makes after LIFF auth to pick which of the four screens to render.
         */
        get: operations["LineRegistrationController_getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/line-users/registration/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the selectable department + personnel-role options.
         * @description Combined payload so the registration/edit form makes ONE call. Returns only NON-deleted options, each list ordered `name ASC`. Ids feed `departmentId`/`personnelRoleId` on register/edit. System-reserved options are never returned.
         */
        get: operations["LineRegistrationController_getOptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/line-users/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit the registration form (UNREGISTERED → PENDING).
         * @description Creates the 1:1 registration for the authenticated LINE user and moves them to `PENDING` (rich menu stays `TYPE_1`). `departmentId`/`personnelRoleId` must reference non-deleted options. Returns the caller’s status view so the frontend can route to the Pending screen without a second call. There is no `lineUserId` body field — the identity is the verified `sub`.
         */
        post: operations["LineRegistrationController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/line-users/registration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit your registration while PENDING (full re-submit).
         * @description A caller whose `access` is strictly `PENDING` may update all their registration fields. `ALLOWED`/`BLOCKED`/`UNREGISTERED` → `403` (no partial write). `access` stays `PENDING` and the rich menu stays `TYPE_1`; no LINE push fires. Same validation as register (options must be non-deleted; a `staffId` taken by another registration → `409`; re-submitting your own is fine). No `lineUserId` body field.
         */
        patch: operations["LineRegistrationController_updateRegistration"];
        trace?: never;
    };
    "/api/v1/line-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List LINE users, paginated.
         * @description Soft-deleted rows are excluded from `data` and from `meta.total`. Optional `search` is a case-insensitive substring match on `displayName`; optional `access` narrows to one state. Ordered `followedAt DESC, id DESC`. A page beyond the last one is a 200 with an empty `data`, not a 404.
         */
        get: operations["LineUsersController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/line-users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Approve or block a LINE user (update `access`).
         * @description Sets `access` (Approve → ALLOWED, Block → BLOCKED). Returns the updated row. ADMIN is bound by the transition matrix (may only reach ALLOWED/BLOCKED, and not from UNREGISTERED); SUPER_ADMIN may set any state and may target soft-deleted rows. An empty body, a bad enum value, or any extra key is a 400.
         */
        patch: operations["LineUsersController_updateAccess"];
        trace?: never;
    };
    "/api/v1/line-users/{id}/registration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit a LINE user's registration fields (admin).
         * @description Full re-submit of firstName, lastName, staffId, phone, departmentId, personnelRoleId. Does NOT change `access` or the rich menu — it is orthogonal to the approve/block transition matrix. Both ADMIN and SUPER_ADMIN may edit. A system-reserved or soft-deleted option id is rejected for every actor (400). For ADMIN a soft-deleted user is 404; SUPER_ADMIN may edit one, with no LINE side-effect.
         */
        patch: operations["LineUsersController_updateRegistrationByAdmin"];
        trace?: never;
    };
    "/api/v1/auth/system/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Issue a CSRF token.
         * @description Safe method, no state change, no session required. Echo the returned token in the `x-csrf-token` header on every state-changing request. The token is not one-shot and survives login.
         */
        get: operations["AuthSystemController_getCsrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/system/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with email + password.
         * @description Sets the `eb.sid` session cookie. Returns the user, never a token. Rate limited to 5 attempts / 15 min per (IP + email) and 20 / 15 min per IP.
         */
        post: operations["AuthSystemController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/system/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Destroy the current session.
         * @description Removes the session from Redis and clears the cookie. A replayed logout returns 401 — the session no longer exists. Reachable while a password change is required.
         */
        post: operations["AuthSystemController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/system/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The currently authenticated back-office user.
         * @description Read fresh from the database on every request (D-9), so a demotion or suspension is reflected immediately. Used to rehydrate a session after a page reload or a backend restart. Reachable while a password change is required — `mustChangePassword` in this body is what the SPA routes off.
         */
        get: operations["AuthSystemController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update your own profile.
         * @description Self-service. Accepts EXACTLY `firstName`, `lastName`, `phoneNumber`, `profilePictureUrl`. `role`, `isActive`, `departmentId`, `personnelRoleId`, `email`, `password` and `lineUserId` are absent from the DTO, so any attempt to set one is a 400 — a SUPER_ADMIN manages those via PATCH /system-users/:id. An empty body is a 400. `phoneNumber`/`profilePictureUrl` accept an explicit null to clear them.
         */
        patch: operations["AuthSystemController_updateOwnProfile"];
        trace?: never;
    };
    "/api/v1/auth/system/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change your own password (forced or voluntary).
         * @description Requires `currentPassword`: without it a hijacked session becomes a permanent account takeover in one request. A WRONG current password is a 400, never a 401 — the session is valid, only the re-auth failed, and a 401 would log you out for a typo. The new password must be >= 12 chars and differ from the current one. On success `mustChangePassword` clears and the very NEXT request to any previously-gated route succeeds on the same cookie — no re-login, because SessionGuard re-reads the user every request. The session is deliberately NOT destroyed.
         */
        post: operations["AuthSystemController_changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/system/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload your own avatar.
         * @description Multipart, one part named `file`. The server enforces size (2 MB) and type: the declared MIME is a first filter only — the real control is a MAGIC-BYTE sniff, and the stored ContentType and key extension are derived from the SNIFFED type, never from the filename. Returns the updated user with `profilePictureUrl` already pointing at the new object; re-render from this body rather than constructing the URL. The CSRF token is a HEADER and works fine with multipart — do not put it in the form body.
         */
        post: operations["AuthSystemController_uploadOwnAvatar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List back-office users, paginated.
         * @description Soft-deleted rows are excluded from `data` and from `meta.total`. Ordered `createdAt DESC, id DESC`. A page beyond the last one is a 200 with an empty `data`, not a 404.
         */
        get: operations["SystemUsersController_list"];
        put?: never;
        /**
         * Create a back-office user.
         * @description The only creation path besides the offline seed script. There is no public registration. The SERVER issues a temporary password and returns it EXACTLY ONCE as `temporaryPassword` — it is argon2id-hashed at rest, never logged, and never retrievable again; deliver it out-of-band. `password` and `lineUserId` are not accepted — any extra key is a 400. `departmentId`/`personnelRoleId` must reference ACTIVE options.
         */
        post: operations["SystemUsersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system-users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read one back-office user.
         * @description A soft-deleted id returns a 404 byte-identical to an id that never existed.
         */
        get: operations["SystemUsersController_findOne"];
        put?: never;
        post?: never;
        /**
         * Soft-delete a back-office user.
         * @description Marks the user as removed; never a hard delete, so the `createdById` audit chain stays resolvable. A second DELETE on the same id is a 404, identical to an id that never existed. Nobody may delete their own account. The email stays permanently burned — restore the row instead of re-creating it.
         */
        delete: operations["SystemUsersController_remove"];
        options?: never;
        head?: never;
        /**
         * Update a back-office user.
         * @description Never the password and never the email. `role` is SUPER_ADMIN-write-only and is rejected on key presence, so an ADMIN sending any valid role value gets 403. Nobody may change their own `role` or `isActive`. An empty body is a 400.
         */
        patch: operations["SystemUsersController_update"];
        trace?: never;
    };
    "/api/v1/system-users/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore a soft-deleted back-office user.
         * @description Un-deletes the row and changes nothing else. A user suspended before deletion comes back suspended; their original password still works. Their `id`, `createdById`, `createdAt`, `role` and `isActive` are unchanged.
         */
        post: operations["SystemUsersController_restore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system-users/{id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue a new temporary password for a user.
         * @description Generates a new temporary password, stores only its argon2id digest, and sets `mustChangePassword` — confining the target to the password-change screen until they set their own. The plaintext is returned EXACTLY ONCE as `temporaryPassword`; deliver it out-of-band. You cannot reset your OWN password (use POST /auth/system/password). A SUSPENDED user is a valid target — the flags are orthogonal — though they still cannot log in.
         */
        post: operations["SystemUsersController_resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List department options.
         * @description Non-deleted options only, ordered `name ASC`. System-reserved options are visible to SUPER_ADMIN only.
         */
        get: operations["DepartmentsController_list"];
        put?: never;
        /**
         * Create a department option.
         * @description A name that collides with an ACTIVE option is a 409; a name matching only soft-deleted rows succeeds (names are reusable after soft-delete).
         */
        post: operations["DepartmentsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Soft-delete a department option.
         * @description Sets `deletedAt`; never a hard delete, so registrations referencing it keep resolving its name. A second DELETE on the same id is a 404. The name becomes reusable. System-reserved options are not deletable and answer 404.
         */
        delete: operations["DepartmentsController_remove"];
        options?: never;
        head?: never;
        /**
         * Rename a department option.
         * @description An unknown or soft-deleted id is a 404; an active-name collision is a 409. System-reserved options are not editable and answer 404.
         */
        patch: operations["DepartmentsController_update"];
        trace?: never;
    };
    "/api/v1/personnel-roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List personnel-role options.
         * @description Non-deleted options only, ordered `name ASC`. System-reserved options are visible to SUPER_ADMIN only.
         */
        get: operations["PersonnelRolesController_list"];
        put?: never;
        /**
         * Create a personnel-role option.
         * @description A name that collides with an ACTIVE option is a 409; a name matching only soft-deleted rows succeeds (names are reusable after soft-delete).
         */
        post: operations["PersonnelRolesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/personnel-roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Soft-delete a personnel-role option.
         * @description Sets `deletedAt`; never a hard delete, so registrations referencing it keep resolving its name. A second DELETE on the same id is a 404. The name becomes reusable. System-reserved options are not deletable and answer 404.
         */
        delete: operations["PersonnelRolesController_remove"];
        options?: never;
        head?: never;
        /**
         * Rename a personnel-role option.
         * @description An unknown or soft-deleted id is a 404; an active-name collision is a 409. System-reserved options are not editable and answer 404.
         */
        patch: operations["PersonnelRolesController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AppInfoResponseDto: {
            /**
             * @description Human-readable confirmation that the service is up.
             * @example EasyBook API is running
             */
            message: string;
            /**
             * @description Coarse service-state banner. Always `active` when the root is reachable; dependency-aware readiness lives at GET /api/v1/health.
             * @example active
             */
            status: string;
            /**
             * @description Server time (ISO 8601) when the banner was produced.
             * @example 2026-07-13T14:45:22.815Z
             */
            timestamp: string;
        };
        HealthResponseDto: {
            /**
             * @description Overall readiness. `ok` (HTTP 200) only when every dependency is `up`; `error` (HTTP 503) when any dependency is `down`.
             * @example ok
             * @enum {string}
             */
            status: "ok" | "error";
            /**
             * @description Process uptime in seconds.
             * @example 12.34
             */
            uptime: number;
            /**
             * @description Server time (ISO 8601) when the probe was answered.
             * @example 2026-06-29T14:45:22.815Z
             */
            timestamp: string;
            /**
             * @description Database connectivity (a `SELECT 1` probe via Prisma).
             * @example up
             * @enum {string}
             */
            db: "up" | "down";
            /**
             * @description Redis connectivity (a `PING` probe). Backs the session store and rate limits.
             * @example up
             * @enum {string}
             */
            redis: "up" | "down";
        };
        LineUserRegistrationResponseDto: {
            /** @example clx1a2b3c4d5e6f7g8h9i0j1 */
            id: string;
            /** @example Somchai */
            firstName: string;
            /** @example Jaidee */
            lastName: string;
            /** @example 6412345678 */
            staffId: string;
            /** @example 081-234-5678 */
            phone: string;
            /**
             * @description Auto-increment integer id.
             * @example 1
             */
            departmentId: number;
            /**
             * @description Resolved department name.
             * @example Computer Science
             */
            department: string;
            /**
             * @description Auto-increment integer id.
             * @example 1
             */
            personnelRoleId: number;
            /**
             * @description Resolved personnel-role name.
             * @example Teacher
             */
            personnelRole: string;
            /** @example 2026-07-14T10:00:00.000Z */
            createdAt: string;
            /** @example 2026-07-14T10:00:00.000Z */
            updatedAt: string;
        };
        LineUserStatusResponseDto: {
            /**
             * @example PENDING
             * @enum {string}
             */
            access: "UNREGISTERED" | "PENDING" | "ALLOWED" | "BLOCKED";
            registration: components["schemas"]["LineUserRegistrationResponseDto"] | null;
        };
        ErrorResponseDto: {
            /** @example 401 */
            statusCode: number;
            /** @example Unauthorized */
            error: string;
            /** @example Invalid email or password. */
            message: string;
        };
        OptionDto: {
            /**
             * @description Auto-increment integer id.
             * @example 1
             */
            id: number;
            /** @example Computer Science */
            name: string;
        };
        RegistrationOptionsResponseDto: {
            departments: components["schemas"]["OptionDto"][];
            personnelRoles: components["schemas"]["OptionDto"][];
        };
        CreateLineUserRegistrationDto: {
            /** @example Somchai */
            firstName: string;
            /** @example Jaidee */
            lastName: string;
            /**
             * @description University staff/personnel ID. Globally unique.
             * @example 6412345678
             */
            staffId: string;
            /** @example 081-234-5678 */
            phone: string;
            /**
             * @description Integer id of a non-deleted Department option (from GET /line-users/registration/options).
             * @example 1
             */
            departmentId: number;
            /**
             * @description Integer id of a non-deleted PersonnelRole option (from GET /line-users/registration/options).
             * @example 1
             */
            personnelRoleId: number;
        };
        UpdateLineUserRegistrationDto: {
            /** @example Somchai */
            firstName: string;
            /** @example Jaidee */
            lastName: string;
            /**
             * @description University staff/personnel ID. Globally unique.
             * @example 6412345678
             */
            staffId: string;
            /** @example 081-234-5678 */
            phone: string;
            /**
             * @description Integer id of a non-deleted Department option (from GET /line-users/registration/options).
             * @example 1
             */
            departmentId: number;
            /**
             * @description Integer id of a non-deleted PersonnelRole option (from GET /line-users/registration/options).
             * @example 1
             */
            personnelRoleId: number;
        };
        LineUserRegistrationSummaryDto: {
            /** @example Somchai */
            firstName: string;
            /** @example Jaidee */
            lastName: string;
            /** @example 6412345678 */
            staffId: string;
            /** @example 081-234-5678 */
            phone: string;
            /**
             * @description Department option FK id.
             * @example 1
             */
            departmentId: number;
            /**
             * @description Resolved department name.
             * @example Computer Science
             */
            department: string;
            /**
             * @description Personnel-role option FK id.
             * @example 1
             */
            personnelRoleId: number;
            /**
             * @description Resolved personnel-role name.
             * @example Teacher
             */
            personnelRole: string;
        };
        LineUserResponseDto: {
            /**
             * @description The LineUser.id (a cuid) — the PATCH /line-users/:id target key.
             * @example clx1a2b3c4d5e6f7g8h9i0j1
             */
            id: string;
            /** @example U0123456789abcdef0123456789abcdef */
            lineUserId: string;
            /** @example Alice */
            displayName: string | null;
            pictureUrl: string | null;
            /** @example Out for lunch 🍜 */
            statusMessage: string | null;
            /**
             * @example TYPE_1
             * @enum {string}
             */
            richMenuType: "TYPE_1" | "TYPE_2";
            /**
             * @example PENDING
             * @enum {string}
             */
            access: "UNREGISTERED" | "PENDING" | "ALLOWED" | "BLOCKED";
            /** @example 2026-07-07T10:00:00.000Z */
            followedAt: string;
            /** @description The user's registration summary, or null for a follower who never submitted the form. */
            registration: components["schemas"]["LineUserRegistrationSummaryDto"] | null;
        };
        PaginationMetaDto: {
            /** @example 1 */
            page: number;
            /** @example 20 */
            limit: number;
            /**
             * @description Non-deleted rows only.
             * @example 42
             */
            total: number;
            /**
             * @description ceil(total / limit); 0 when total is 0.
             * @example 3
             */
            totalPages: number;
        };
        PaginatedLineUsersResponseDto: {
            data: components["schemas"]["LineUserResponseDto"][];
            meta: components["schemas"]["PaginationMetaDto"];
        };
        UpdateLineUserAccessDto: {
            /**
             * @description The user's new access state. Approve → ALLOWED, Block → BLOCKED (the frontend never sends PENDING, but it is accepted).
             * @example ALLOWED
             * @enum {string}
             */
            access: "UNREGISTERED" | "PENDING" | "ALLOWED" | "BLOCKED";
        };
        AdminUpdateLineUserRegistrationDto: {
            /** @example Somchai */
            firstName: string;
            /** @example Jaidee */
            lastName: string;
            /**
             * @description University staff/personnel ID. Globally unique.
             * @example 6412345678
             */
            staffId: string;
            /** @example 081-234-5678 */
            phone: string;
            /**
             * @description Integer id of a non-deleted Department option (from GET /line-users/registration/options).
             * @example 1
             */
            departmentId: number;
            /**
             * @description Integer id of a non-deleted PersonnelRole option (from GET /line-users/registration/options).
             * @example 1
             */
            personnelRoleId: number;
        };
        CsrfTokenResponseDto: {
            /**
             * @description Send as the `x-csrf-token` header on state-changing requests.
             * @example a3f1c0d9e8b7…
             */
            csrfToken: string;
        };
        LoginDto: {
            /** @example admin@easybook.local */
            email: string;
            /**
             * Format: password
             * @example correct horse battery staple
             */
            password: string;
        };
        LoginResponseDto: {
            /** @example clx1a2b3c4d5e6f7g8h9i0j1 */
            id: string;
            /** @example admin@easybook.local */
            email: string;
            /** @example Ada */
            firstName: string;
            /** @example Lovelace */
            lastName: string;
            /**
             * @example ADMIN
             * @enum {string}
             */
            role: "SUPER_ADMIN" | "ADMIN" | "STAFF";
        };
        SystemUserOptionDto: {
            /** @example 3 */
            id: number;
            /** @example Computer Science */
            name: string;
        };
        SystemUserResponseDto: {
            /** @example clx1a2b3c4d5e6f7g8h9i0j1 */
            id: string;
            /** @example admin@easybook.local */
            email: string;
            /** @example Ada */
            firstName: string;
            /** @example Lovelace */
            lastName: string;
            /**
             * @description Back-office RBAC. The ONLY field that grants privilege — never `personnelRole`.
             * @example STAFF
             * @enum {string}
             */
            role: "SUPER_ADMIN" | "ADMIN" | "STAFF";
            department: components["schemas"]["SystemUserOptionDto"];
            /** @description Job title. NOT `role` — grants zero privilege. */
            personnelRole: components["schemas"]["SystemUserOptionDto"];
            /**
             * @description True while a temp password is outstanding; every route except logout / GET me / POST password answers 403.
             * @example false
             */
            mustChangePassword: boolean;
            /** @example 02-123-4567 ext. 101 */
            phoneNumber: string | null;
            /** @example https://cdn.example.com/a.jpg */
            profilePictureUrl: string | null;
            /** @example true */
            isActive: boolean;
            /**
             * @description Linked LineUser.id (a cuid), or null. NOT the LINE "U…" identifier. Read-only; set by a future endpoint.
             * @example clx9z8y7x6w5v4u3t2s1r0q9
             */
            readonly lineUserId: string | null;
            /** @example 2026-07-08T11:00:00.000Z */
            lastLoginAt: string | null;
            /** @example 2026-07-08T10:00:00.000Z */
            createdAt: string;
        };
        UpdateOwnProfileDto: {
            /** @example Ada */
            firstName?: string;
            /** @example Lovelace */
            lastName?: string;
            /** @example 02-123-4567 ext. 101 */
            phoneNumber?: string | null;
            profilePictureUrl?: string | null;
        };
        ChangePasswordDto: {
            /** Format: password */
            currentPassword: string;
            /** Format: password */
            newPassword: string;
        };
        CreateSystemUserDto: {
            /** @example ada@easybook.local */
            email: string;
            /** @example Ada */
            firstName: string;
            /** @example Lovelace */
            lastName: string;
            /**
             * @default STAFF
             * @enum {string}
             */
            role: "SUPER_ADMIN" | "ADMIN" | "STAFF";
            /**
             * @description Department option id. Must reference an ACTIVE (non-soft-deleted) option — otherwise 400.
             * @example 3
             */
            departmentId: number;
            /**
             * @description PersonnelRole option id — the job title ("Position" in the UI). NOT `role`; grants zero privilege. Must reference an ACTIVE option — otherwise 400.
             * @example 5
             */
            personnelRoleId: number;
            /** @example 02-123-4567 ext. 101 */
            phoneNumber?: string;
            /** @example https://cdn.example.com/avatars/ada.jpg */
            profilePictureUrl?: string;
        };
        SystemUserWithTemporaryPasswordDto: {
            /** @example clx1a2b3c4d5e6f7g8h9i0j1 */
            id: string;
            /** @example admin@easybook.local */
            email: string;
            /** @example Ada */
            firstName: string;
            /** @example Lovelace */
            lastName: string;
            /**
             * @description Back-office RBAC. The ONLY field that grants privilege — never `personnelRole`.
             * @example STAFF
             * @enum {string}
             */
            role: "SUPER_ADMIN" | "ADMIN" | "STAFF";
            department: components["schemas"]["SystemUserOptionDto"];
            /** @description Job title. NOT `role` — grants zero privilege. */
            personnelRole: components["schemas"]["SystemUserOptionDto"];
            /**
             * @description True while a temp password is outstanding; every route except logout / GET me / POST password answers 403.
             * @example false
             */
            mustChangePassword: boolean;
            /** @example 02-123-4567 ext. 101 */
            phoneNumber: string | null;
            /** @example https://cdn.example.com/a.jpg */
            profilePictureUrl: string | null;
            /** @example true */
            isActive: boolean;
            /**
             * @description Linked LineUser.id (a cuid), or null. NOT the LINE "U…" identifier. Read-only; set by a future endpoint.
             * @example clx9z8y7x6w5v4u3t2s1r0q9
             */
            readonly lineUserId: string | null;
            /** @example 2026-07-08T11:00:00.000Z */
            lastLoginAt: string | null;
            /** @example 2026-07-08T10:00:00.000Z */
            createdAt: string;
            /**
             * @description SHOWN EXACTLY ONCE. Not stored in plaintext, not retrievable, not logged. Deliver it out-of-band; the recipient must change it at first login.
             * @example Kp7Rn2Tq9Wx4Yb6C
             */
            temporaryPassword: string;
        };
        PaginatedSystemUsersResponseDto: {
            data: components["schemas"]["SystemUserResponseDto"][];
            meta: components["schemas"]["PaginationMetaDto"];
        };
        UpdateSystemUserDto: {
            /** @example Ada */
            firstName?: string;
            /** @example Lovelace */
            lastName?: string;
            /**
             * @description Department option id.
             * @example 3
             */
            departmentId?: number;
            /**
             * @description PersonnelRole option id — the job title ("Position" in the UI). NOT `role`; grants zero privilege.
             * @example 5
             */
            personnelRoleId?: number;
            /** @example 02-123-4567 ext. 101 */
            phoneNumber?: string | null;
            profilePictureUrl?: string | null;
            /** @enum {string} */
            role?: "SUPER_ADMIN" | "ADMIN" | "STAFF";
            /** @example false */
            isActive?: boolean;
        };
        DepartmentResponseDto: {
            /**
             * @description Auto-increment integer id.
             * @example 1
             */
            id: number;
            /** @example Computer Science */
            name: string;
            /**
             * @description READ-ONLY. True only for the System-Developer-owned reserved row (visible to SUPER_ADMIN only; always false for everyone else). Settable by no endpoint.
             * @example false
             */
            isSystemReserved: boolean;
            /** @example 2026-07-14T10:00:00.000Z */
            createdAt: string;
            /** @example 2026-07-14T10:00:00.000Z */
            updatedAt: string;
        };
        CreateDepartmentDto: {
            /** @example Computer Science */
            name: string;
        };
        UpdateDepartmentDto: {
            /** @example Computer Engineering */
            name: string;
        };
        PersonnelRoleResponseDto: {
            /**
             * @description Auto-increment integer id.
             * @example 1
             */
            id: number;
            /** @example Teacher */
            name: string;
            /**
             * @description READ-ONLY. True only for the System-Developer-owned reserved row (visible to SUPER_ADMIN only; always false for everyone else). Settable by no endpoint.
             * @example false
             */
            isSystemReserved: boolean;
            /** @example 2026-07-14T10:00:00.000Z */
            createdAt: string;
            /** @example 2026-07-14T10:00:00.000Z */
            updatedAt: string;
        };
        CreatePersonnelRoleDto: {
            /** @example Teacher */
            name: string;
        };
        UpdatePersonnelRoleDto: {
            /** @example Senior Lecturer */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service is up and serving requests. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppInfoResponseDto"];
                };
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready: the database and Redis are both reachable. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseDto"];
                };
            };
            /** @description Service is not ready: the database and/or Redis is unreachable. Body carries the per-dependency breakdown. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseDto"];
                };
            };
        };
    };
    LineRegistrationController_getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller’s current status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineUserStatusResponseDto"];
                };
            };
            /** @description Missing/invalid/expired/wrong-aud LINE ID token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description LINE verification endpoint unreachable (retryable). */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    LineRegistrationController_getOptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The available options. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationOptionsResponseDto"];
                };
            };
            /** @description Missing/invalid/expired/wrong-aud LINE ID token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description LINE verification endpoint unreachable (retryable). */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    LineRegistrationController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLineUserRegistrationDto"];
            };
        };
        responses: {
            /** @description Registered; access is now PENDING. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineUserStatusResponseDto"];
                };
            };
            /** @description Missing/blank field, bad phone, a deleted/unknown option id, or an unknown extra key. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Missing/invalid/expired/wrong-aud LINE ID token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Already registered, or the staff ID is taken. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description LINE verification endpoint unreachable (retryable). */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    LineRegistrationController_updateRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLineUserRegistrationDto"];
            };
        };
        responses: {
            /** @description Updated; still PENDING. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineUserStatusResponseDto"];
                };
            };
            /** @description Missing/blank field, bad phone, a deleted/unknown option id, or an unknown extra key. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Missing/invalid/expired/wrong-aud LINE ID token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description The caller is not PENDING (ALLOWED / BLOCKED / UNREGISTERED). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description The staff ID is taken by another registration. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description LINE verification endpoint unreachable (retryable). */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    LineUsersController_list: {
        parameters: {
            query?: {
                /** @description 1-based page number. */
                page?: number;
                limit?: number;
                /** @description Case-insensitive substring match on `displayName`. Trimmed; empty/absent → no name filter. */
                search?: string;
                /** @description Narrows the list to a single access state. An invalid value is a 400. */
                access?: "UNREGISTERED" | "PENDING" | "ALLOWED" | "BLOCKED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of LINE users. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedLineUsersResponseDto"];
                };
            };
            /** @description No session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description STAFF has no access to this collection. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Session store unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    LineUsersController_updateAccess: {
        parameters: {
            query?: never;
            header: {
                "x-csrf-token": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLineUserAccessDto"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineUserResponseDto"];
                };
            };
            /** @description No session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description STAFF; CSRF failure; or an access transition not permitted for ADMIN. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Unknown id (both roles); a soft-deleted id is 404 for ADMIN but targetable by SUPER_ADMIN. Reveals nothing about deletion. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Session store unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    LineUsersController_updateRegistrationByAdmin: {
        parameters: {
            query?: never;
            header: {
                "x-csrf-token": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUpdateLineUserRegistrationDto"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineUserResponseDto"];
                };
            };
            /** @description Malformed/blank field, bad phone, an extra key (including `lineUserId`), or a deleted/unknown/system-reserved option id. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description No session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description STAFF, or a CSRF failure. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Unknown id (both roles); a soft-deleted id for ADMIN; or the user exists but has no registration to edit. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description The `staffId` is taken by another registration (P2002). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Session store unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthSystemController_getCsrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A CSRF token and its signed cookie. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfTokenResponseDto"];
                };
            };
        };
    };
    AuthSystemController_login: {
        parameters: {
            query?: never;
            header: {
                /** @description From `GET /auth/system/csrf`. */
                "x-csrf-token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Authenticated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
            /** @description Unknown email, wrong password, suspended, or deleted — one identical response. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Missing or stale CSRF token. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Rate limited. Carries a `Retry-After` header. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Session store unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthSystemController_logout: {
        parameters: {
            query?: never;
            header: {
                "x-csrf-token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session destroyed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                    };
                };
            };
            /** @description No, expired, or already-destroyed session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Missing or stale CSRF token. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Session store unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthSystemController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemUserResponseDto"];
                };
            };
            /** @description No session, expired, suspended, or deleted user. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Session store unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthSystemController_updateOwnProfile: {
        parameters: {
            query?: never;
            header: {
                "x-csrf-token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOwnProfileDto"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemUserResponseDto"];
                };
            };
            /** @description Empty body, a forbidden key, or a bad value. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description No session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description CSRF failure, or a password change is required. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Session store unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthSystemController_changePassword: {
        parameters: {
            query?: never;
            header: {
                "x-csrf-token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDto"];
            };
        };
        responses: {
            /** @description Password changed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                    };
                };
            };
            /** @description Validation failed, the current password is wrong, or the new password matches the current one. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description No session — or a suspended/deleted user, which fires first. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Missing or stale CSRF token. NEVER the forced-reset gate. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Session store unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthSystemController_uploadOwnAvatar: {
        parameters: {
            query?: never;
            header: {
                "x-csrf-token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description JPEG, PNG or WEBP. Max 2 MB.
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Uploaded. The updated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemUserResponseDto"];
                };
            };
            /** @description No file, wrong field name, unsupported/mismatched image type, or larger than 2 MB. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description No session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description CSRF failure, or a password change is required. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description The object store rejected the upload or was unreachable. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Session store unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    SystemUsersController_list: {
        parameters: {
            query?: {
                /** @description 1-based page number. */
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of users. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSystemUsersResponseDto"];
                };
            };
            /** @description No session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description STAFF has no access to this collection. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Session store unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    SystemUsersController_create: {
        parameters: {
            query?: never;
            header: {
                "x-csrf-token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSystemUserDto"];
            };
        };
        responses: {
            /** @description Created. Carries the one-time `temporaryPassword`. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemUserWithTemporaryPasswordDto"];
                };
            };
            /** @description Validation failed, or departmentId/personnelRoleId is unknown or soft-deleted. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description No session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Not a SUPER_ADMIN, CSRF failure, or a password change is required. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description That email is already taken (including by a soft-deleted user). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Session store unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    SystemUsersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemUserResponseDto"];
                };
            };
            /** @description No session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description STAFF has no access to this collection. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Unknown or soft-deleted id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Session store unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    SystemUsersController_remove: {
        parameters: {
            query?: never;
            header: {
                "x-csrf-token": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Soft-deleted. Empty body. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Not a SUPER_ADMIN; CSRF failure; or deleting your own account. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Unknown or already-deleted id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Would remove the last active SUPER_ADMIN, or lost a concurrent-write race. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Session store unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    SystemUsersController_update: {
        parameters: {
            query?: never;
            header: {
                "x-csrf-token": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSystemUserDto"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemUserResponseDto"];
                };
            };
            /** @description No session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description STAFF; CSRF failure; a self-mutation rule; or a policy denial. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Unknown or soft-deleted id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Would remove the last active SUPER_ADMIN, or lost a concurrent-write race. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Session store unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    SystemUsersController_restore: {
        parameters: {
            query?: never;
            header: {
                "x-csrf-token": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Restored. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemUserResponseDto"];
                };
            };
            /** @description No session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Not a SUPER_ADMIN, or CSRF failure. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Unknown id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description The row is not deleted. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Session store unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    SystemUsersController_resetPassword: {
        parameters: {
            query?: never;
            header: {
                "x-csrf-token": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reset. Carries the one-time `temporaryPassword`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemUserWithTemporaryPasswordDto"];
                };
            };
            /** @description No session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Not a SUPER_ADMIN; CSRF failure; resetting your own password; or a password change is required. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Unknown or soft-deleted id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Session store unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    DepartmentsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The options. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentResponseDto"][];
                };
            };
            /** @description No session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description STAFF has no access. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Session store unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    DepartmentsController_create: {
        parameters: {
            query?: never;
            header: {
                "x-csrf-token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDepartmentDto"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentResponseDto"];
                };
            };
            /** @description No session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description STAFF, or CSRF failure. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description An active option with this name already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Session store unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    DepartmentsController_remove: {
        parameters: {
            query?: never;
            header: {
                "x-csrf-token": string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Soft-deleted. Empty body. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description STAFF, or CSRF failure. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Unknown or already-deleted id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Session store unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    DepartmentsController_update: {
        parameters: {
            query?: never;
            header: {
                "x-csrf-token": string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDepartmentDto"];
            };
        };
        responses: {
            /** @description Renamed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentResponseDto"];
                };
            };
            /** @description No session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description STAFF, or CSRF failure. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Unknown or soft-deleted id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description An active option with this name already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Session store unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    PersonnelRolesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The options. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonnelRoleResponseDto"][];
                };
            };
            /** @description No session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description STAFF has no access. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Session store unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    PersonnelRolesController_create: {
        parameters: {
            query?: never;
            header: {
                "x-csrf-token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePersonnelRoleDto"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonnelRoleResponseDto"];
                };
            };
            /** @description No session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description STAFF, or CSRF failure. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description An active option with this name already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Session store unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    PersonnelRolesController_remove: {
        parameters: {
            query?: never;
            header: {
                "x-csrf-token": string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Soft-deleted. Empty body. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description STAFF, or CSRF failure. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Unknown or already-deleted id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Session store unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    PersonnelRolesController_update: {
        parameters: {
            query?: never;
            header: {
                "x-csrf-token": string;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePersonnelRoleDto"];
            };
        };
        responses: {
            /** @description Renamed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonnelRoleResponseDto"];
                };
            };
            /** @description No session. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description STAFF, or CSRF failure. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Unknown or soft-deleted id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description An active option with this name already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Session store unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
}
